Crafting = {
	SmeltMenu = {
		Header = locale("info", "use_smelter"),
		progressBar = { label = locale("info", "smelting"), time = Config.Timings["Crafting"], },
		Recipes = {
		--  { ["output"] 		= { ["input"] = 1, }, ['input_amount'] = 2 },
			{ ["sulfur"] 		= { ["sulfurore"] = 3 } },
			{ ["ironnugget"] 	= { ["ironore"] = 3 } },
			{ ["leadnugget"] 	= { ["leadore"] = 3 } },
			{ ["coppernugget"] 	= { ["copperore"] = 3 } },
			{ ["charcoal"] 		= { ["coal"] = 3 } },
			{ ["silvernugget"] 	= { ["silverore"] = 3 } },
			{ ["goldnugget"] 	= { ["goldore"] = 3 } },
			{ ["ironingot"] 	= { ["ironnugget"] = 1 } },
			{ ["leadingot"] 	= { ["leadnugget"] = 1 } },
			{ ["copperingot"] 	= { ["coppernugget"] = 1 } },
			{ ["silveringot"] 	= { ["silvernugget"] = 1, } },
			{ ["goldingot"] 	= { ["goldnugget"] = 1, } },
		},
	},
	GemCut = {
		Header = locale("info", "gem_cut"),
		progressBar = { label = locale("info", "cutting"), time = Config.Timings["Crafting"], },
		anims = { anim = "operate_02_hi_amy_skater_01", animDict = "anim@amb@machinery@speed_drill@" },
		Recipes = {
			{ ["sapphire"] 		= { ["uncut_sapphire"] = 1 }, },
			{ ["ruby"] 			= { ["uncut_ruby"] = 1 }, },
			{ ["emerald"] 		= { ["uncut_emerald"] = 1, } },
			{ ["diamond"] 		= { ["uncut_diamond"] = 1}, },
		},
	},
	RingCut = {
		Header = locale("info", "rings"),
		progressBar = { label = locale("info", "cutting"), time = Config.Timings["Crafting"], },
		anims = { anim = "operate_02_hi_amy_skater_01", animDict = "anim@amb@machinery@speed_drill@" },
		Recipes = {
			{ ["gold_diamond_ring"] 		= { ["goldnugget"] = 3, ["diamond"] = 1 }, },
			{ ["gold_emerald_ring"] 		= { ["goldnugget"] = 3, ["emerald"] = 1 }, },
			{ ["gold_ruby_ring"] 			= { ["goldnugget"] = 3, ["ruby"] = 1 }, },
			{ ["gold_sapphire_ring"] 		= { ["goldnugget"] = 3, ["sapphire"] = 1 }, },

			{ ["silver_diamond_ring"] 		= { ["silvernugget"] = 3, ["diamond"] = 1 }, },
			{ ["silver_emerald_ring"] 		= { ["silvernugget"] = 3, ["emerald"] = 1 }, },
			{ ["silver_ruby_ring"] 			= { ["silvernugget"] = 3, ["ruby"] = 1 }, },
			{ ["silver_sapphire_ring"] 		= { ["silvernugget"] = 3, ["sapphire"] = 1 }, },
		},
	},
	NeckCut = {
		Header = locale("info", "necklaces"),
		progressBar = { label = locale("info", "cutting"), time = Config.Timings["Crafting"], },
		anims = { anim = "operate_02_hi_amy_skater_01", animDict = "anim@amb@machinery@speed_drill@" },
		Recipes = {
			{ ["gold_diamond_necklace"] 	= { ["goldnugget"] = 6, ["diamond"] = 1 }, },
			{ ["gold_emerald_necklace"] 	= { ["goldnugget"] = 6, ["emerald"] = 1 }, },
			{ ["gold_ruby_necklace"] 		= { ["goldnugget"] = 6, ["ruby"] = 1 }, },
			{ ["gold_sapphire_necklace"] 	= { ["goldnugget"] = 6, ["sapphire"] = 1 }, },

			{ ["silver_diamond_necklace"] 	= { ["silvernugget"] = 6, ["diamond"] = 1 }, },
			{ ["silver_emerald_necklace"] 	= { ["silvernugget"] = 6, ["emerald"] = 1 }, },
			{ ["silver_ruby_necklace"] 		= { ["silvernugget"] = 6, ["ruby"] = 1 }, },
			{ ["silver_sapphire_necklace"] 	= { ["silvernugget"] = 6, ["sapphire"] = 1 }, },
		},
	},
	EarCut = {
		Header = locale("info", "earrings"),
		progressBar = { label = locale("info", "cutting"), time = Config.Timings["Crafting"], },
		anims = { anim = "operate_02_hi_amy_skater_01", animDict = "anim@amb@machinery@speed_drill@" },
		Recipes = {
			{ ["gold_diamond_earring"] 		= { ["goldnugget"] = 2, ["diamond"] = 2 }, },
			{ ["gold_emerald_earring"] 		= { ["goldnugget"] = 2, ["emerald"] = 2 }, },
			{ ["gold_ruby_earring"] 		= { ["goldnugget"] = 2, ["ruby"] = 2 }, },
			{ ["gold_sapphire_earring"] 	= { ["goldnugget"] = 2, ["sapphire"] = 2 }, },

			{ ["silver_diamond_earring"] 	= { ["silvernugget"] = 2, ["diamond"] = 2 }, },
			{ ["silver_emerald_earring"] 	= { ["silvernugget"] = 2, ["emerald"] = 2 }, },
			{ ["silver_ruby_earring"] 		= { ["silvernugget"] = 2, ["ruby"] = 2 }, },
			{ ["silver_sapphire_earring"] 	= { ["silvernugget"] = 2, ["sapphire"] = 2 }, },
		},
	},
}
